jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: nazneen_jeevunjee
      password: <password>
      port: 5432
      dbname: jaffle_shop
      schema: central_insights_sandbox
      threads: 4
